### ISSUE TITLE
despite pip3 install ib, it don't work

### ISSUE THREAD

**Issue by jprus** [EDByte/EDB#1]
Traceback (most recent call last):
  File "loop.py", line 11, in <module>
    from ib_execution import ExecutionHandler
  File "/home/jprus/EDB/ib_execution.py", line 3, in <module>
    from ib.ext.Contract import Contract
ModuleNotFoundError: No module named 'ib'

**Comment by rodcoelho** [comment]
https://www.quantstart.com/articles/Using-Python-IBPy-and-the-Interactive-Brokers-API-to-Automate-Trades

**Comment by jprus** [comment]
pip3 install IbPy2
